print(type(5))
print(type(10.0))
print(type("napis"))
print(type('a'))
print(type(5) == type(10))
print(type(True))
print(type(type(5) != type(10)))
print(type(True) == type(False))

print(type([1, 2, 3]))
print(type({"Nj" : "Trentom"}))
